package com.seanjd.devart.models
{
	import away3d.core.base.Geometry;
	import away3d.materials.ColorMaterial;
	import away3d.materials.MaterialBase;
	import away3d.primitives.SphereGeometry;
	import com.seanjd.devart.DifferenceEngine;
	import com.seanjd.devart.views.ParticleContainer;
	
	/**
	 * ...
	 * @author SJD
	 */
	
	public class SignatureData{
		
		//hardcoded for now, these values will be generated by user data such as heart rate
		private const NUM_PARTICLES:int = 6;
		private var _positions:Vector.<Point3D> = new Vector.<Point3D>;
		private var _geoms:Vector.<Geometry> = new Vector.<Geometry>;
		private var _mats:Vector.<MaterialBase> = new Vector.<MaterialBase>;
		
		public function SignatureData() {
			
			_positions.push(new Point3D());//particle 1 at 0,0,0
			_positions.push(new Point3D(3,3));
			_positions.push(new Point3D(0,0,-4));
			_positions.push(new Point3D(-3,1,1));
			_positions.push(new Point3D(-1,6,-1));
			_positions.push(new Point3D(1, 4, 0));
			
			var sizes:Array = [2.5, 1.8, 1.8, 1.6, 1.4, 1.3];
			
			for (var i:uint = 0; i < NUM_PARTICLES; i++) {
				_geoms.push(new SphereGeometry(sizes[i]));
			}
			
		}
		
		private function createGeom(i:uint):Geometry {
			//just create spheres for now for simplicity
			var sphere:SphereGeometry = new SphereGeometry(2 + Math.random() * 4);
			return sphere;
		}
		
		
		private function createMat(i:uint):MaterialBase {
			var material:ColorMaterial = new ColorMaterial(0xCCCCCC);// (Math.random() * 0xFFFFFF);
			material.lightPicker = DifferenceEngine.lightPicker;
			return material;
		}
		
		public function get positions():Vector.<Point3D> {
			return _positions;
		}
		public function get geoms():Vector.<Geometry> {
			return _geoms;
		}
		public function get mats():Vector.<MaterialBase> {
			return _mats;
		}
	
	}

}